package CPP.Absyn; // Java Package generated by the BNF Converter.

public class ListId extends java.util.LinkedList<String> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7446770240572376140L;
}

//public class ListId extends java.util.LinkedList<Exp> {
//}
