package CPP.Absyn; // Java Package generated by the BNF Converter.

public class Type_void extends Type {
  /**
	 * 
	 */
	private static final long serialVersionUID = 2085790489637536897L;

public Type_void() { }

  public <R,A> R accept(CPP.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof CPP.Absyn.Type_void) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
